name: ecloud

on:
  push:
  schedule:
    - cron: 5 0 * * *
  workflow_dispatch:

jobs:
  ecloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: 3.7

      - name: 安装依赖
        run: |
          pip3 install -r requirements.txt

      - name: 开始签到
        run: |
          python3 ecloud.py