name: 天翼云盘自动签到

on:
  push:
  schedule:
    - cron: 5 0 * * *
  workflow_dispatch:

jobs:
  sign-in:
    env:
      USERNAME: 13781850816
      PASSWORD: Caoyuze990318
      PUSHER_WECHAT: ww1b63035144a6d2f1,kGJl9yYUy-mQXCO5hulxCId5L2sVaKW2HKeqyguhytg,@all,1000002,2168tjb8CL3KTeit4o6wZrlFsKpdTdnkCirm9C-bBK97_-7JzKe7iEN362UAmp54P
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: 安装环境
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: 安装依赖
        run: |
          pip3 install -r requirements.txt
      - name: 开始签到
        run: |
          python3 ecloud.py