name: 天翼云盘自动签到

on:
  push:
    branches:
      - master
  schedule:
    - cron: 5 0 * * *

jobs:
  sign-in:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: 安装环境
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: 安装依赖
        run: |
          pip3 install -r requirements.txt
      - name: 开始签到
        run: |
          python3 ecloud.py